### PR TITLE
fix #11

### LINKED ISSUE #11: Add ability to set a className of the outer component
This will be useful when people want to apply their own stylesheet so they can scope their selectors properly

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by longlho** [comment]
ping @pedronauck

**Comment by pedronauck** [comment]
It's done @longlho, sorry not to accept before :)

cc: @Munter

**Comment by longlho** [comment]
thanks! @pedronauck  :)

**Comment by Munter** [comment]
Awesome :D

**Comment by longlho** [comment]
@pedronauck can u publish `0.6.0` also please :)

**Comment by pedronauck** [comment]
It's done @longlho :)

**Pull request merged**
