### PR TITLE
Render all panels, but show only active one

### PR DESCRIPTION
**Pull request by i7an**
I would expect panels to keep state while switching the tabs.

### CODE REVIEW

**Comment by popc0rn** [comment]
+ 1 for this but as an optional feature.

In one case I need to load bundled data that is then used across multiple tabs. The problem is that one tab contains svg graph which takes time to render. This creates a problem with original behavior because it generates noticeable delay while switching tabs and the data(graph) stays the same the whole time so all of that is not necessary.

**Comment by Galathius** [comment]
:100: :100: :100:

**Comment by i7an** [comment]
@popc0rn if you worry about performance or rerenders use shouldComponentUpdate method. For my taste unmounting and mounting component each time you change tab is unexpected.

**Comment by popc0rn** [comment]
@i7an Hi! Without going into the code again... I don't think I can do that since react-simpletabs renders only the active tab, right? So there is no point in rechecking if something inside non active tab  should rerender when it becomes active again. There is no that type of control since nonactive tabs are discarded from the DOM.
Thanks for replying!

**Pull request closed without merging**
